version: '3.8'

x-service-templates:
  backend: &backend
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    networks:
      - payment-processor
      - backend
    expose:
      - 3000
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/rinha?authSource=admin
      - PAYMENT_PROCESSOR_SERVICE_DEFAULT_URL=http://localhost:8001
      - PAYMENT_PROCESSOR_SERVICE_FALLBACK_URL=http://localhost:8002
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "1GB"
        reservations:
          cpus: "0.5"
          memory: "512MB"
    restart: unless-stopped

services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    hostname: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
      - MONGO_INITDB_DATABASE=rinha
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "1GB"
        reservations:
          cpus: "0.5"
          memory: "512MB"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  backend-01:
    <<: *backend
    container_name: backend-01
    hostname: backend-01
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/rinha?authSource=admin
      - INSTANCE_ID=01
      - PAYMENT_PROCESSOR_SERVICE_DEFAULT_URL=http://localhost:8001
      - PAYMENT_PROCESSOR_SERVICE_FALLBACK_URL=http://localhost:8002
      - INSTANCE_ID=01

  backend-02:
    <<: *backend
    container_name: backend-02
    hostname: backend-02
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/rinha?authSource=admin
      - INSTANCE_ID=02
      - PAYMENT_PROCESSOR_SERVICE_DEFAULT_URL=http://localhost:8001
      - PAYMENT_PROCESSOR_SERVICE_FALLBACK_URL=http://localhost:8002
      - INSTANCE_ID=02
  nginx:
    image: nginx:alpine
    container_name: load-balancer
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend-01
      - backend-02
    ports:
      - "9999:9999"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "64MB"
        reservations:
          cpus: "0.1"
          memory: "32MB"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9999/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true

volumes:
  mongodb_data:
    driver: local 